### ISSUE TITLE
Ver video clase lab

### ISSUE THREAD

**Issue by UO277348** [Arquisoft/dede_es3b#11]
https://www.youtube.com/watch?v=wgpSdpny-0c
- [x] Daniel Pascual
- [x] José Rodríguez
- [x] Martín Fernández
- [x] Tania Bajo
- [x] Pablo Rodríguez

**Comment by PascualDaniel** [comment]
[Ark42 Biking](https://biking.michael-simons.eu/docs/index.html)
Enlace a un ejemplo de documentación.
