### ISSUE TITLE
Preguntas sobre los test

### ISSUE THREAD

**Issue by UO277348** [Arquisoft/dede_es3b#118]
Buenas tardes,
Pensando como hacer los test del front-end nos hemos encontrado con el problema de coger los datos. Decís que no cojamos datos de la BBDD sino que creemos nosotros esos datos para la prueba. La pregunta es cómo podemos coger/usar variables/métodos definidos en la variable App (donde están toda la funcionalidad) para poder adecuarlo a las pruebas.
Un saludo y disculpa las molestias

**Comment by HugoLebredo** [comment]
Lo que suele hacerse es crear otra variable app antes de los tests sobre la que trabajan los tests.

En cuanto a inyectar datos para un test. Es bastante sencillo, lo que hay que hacer dentro del test crear tus variables con los datos a probar.
Te paso un par de repositorios en los que hay tests hechos.

👉 En este repo teneis algunos ejemplos de pruebas de backend https://github.com/HugoLebredo/notes-app-backend
👉 En este otro de frontend (react) https://github.com/HugoLebredo/WEATHER-APP

Checkea como van, no tiene mucha complejidad
