### ISSUE TITLE
Problemas con el despliegue en Heroku

### ISSUE THREAD

**Issue by uo277084** [Arquisoft/dede_es3b#143]
Hemos intentado desplegarlo mediante Container Registry, pero sólo se desplegaba webapp y fallaba. Además, se estaba desplegando en Estados Unidos. Respecto a GitHub. Después de enlazar GitHub con Heroku, intentamos desplegarlo pero daba errores.

**Comment by PascualDaniel** [comment]
Voy a intentar eliminar el pacage-lock.json que creo que es lo que esta dando error

**Comment by PascualDaniel** [comment]
Eso a funcionado pero crashea al entrar

**Comment by PascualDaniel** [comment]
me da este error:
`2022-04-05T17:57:29.780358+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=dedeportes.herokuapp.com request_id=d5eddf5b-3a2f-4c76-8bad-a5ed8c33e1c1 fwd="92.172.212.29" dyno= connect= service= status=503 bytes= protocol=https`

**Comment by PascualDaniel** [comment]
@HugoLebredo

**Comment by HugoLebredo** [comment]
Hola chicos.
Siento deciros que no soy ningún experto en Heroku.
Dicho esto se me ocurre que cambieis de estrategia. Haced un flujo de trabajo sin las pruebas e2e (que por lo que veo ahora os falla). Primeramente pasad los tests unitarios de frontend y backend, después crear la imágenes de docker y finalmente que despliegue Heroku.
Integración continua vais a tener que hacer obligatoriamente y creo que será mas sencillo encontrar un trabajo que haga ese despliegue que seguir el camino que iniciasteis.
HE encontrado esto https://github.com/marketplace/actions/deploy-docker-image-to-heroku-app. Ojo que necesitáis desplegar 2 imagenes y que se comuniquen.

**Comment by PascualDaniel** [comment]
Cierro esto ya que lo vamos a hacer en AWS
