### ISSUE TITLE
Error al desplegar en AWS

### ISSUE THREAD

**Issue by PascualDaniel** [Arquisoft/dede_es3b#165]
No entiendo muy bien que significa el error al hacer el deploy por ssh
`/usr/bin/docker run --name b31b289577[14](https://github.com/Arquisoft/dede_es3b/runs/6096900295?check_suite_focus=true#step:3:14)abb4330b6153f01e0bbc29a_f718ef --label 294b31 --workdir /github/workspace --rm -e INPUT_HOST -e INPUT_USER -e INPUT_KEY -e INPUT_COMMAND -e INPUT_PORT -e INPUT_KEYFILE -e INPUT_PASS -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/dede_es3b/dede_es3b":"/github/workspace" 294b31:b28957714abb4330b6153f01e0bbc29a
 Warning: This action does not currently support host verification; verification is disabled.`

**Comment by PascualDaniel** [comment]
Segun pone es porque  no encuentra del docker-compose 

-bash: line 2: docker-compose: command not found
-bash: line 3: docker-compose: command not found
-bash: line 4: docker-compose: command not found
-bash: line 5: docker-compose: command not found

**Comment by HugoLebredo** [comment]
He cambiado los permisos de los paquetes de docker. Por defecto son privados y eso hace que no puedan desplegarse. Ahora son públicos. Intentad desplegar de nuevo

**Comment by PascualDaniel** [comment]
Vale ahora parece que por lo menos lo empieza a subir, pero da este error:

ERROR: for webapp  invalid reference format: repository name must be lowercase

ERROR: for restapi  invalid reference format: repository name must be lowercase
invalid reference format: repository name must be lowercase
invalid reference format: repository name must be lowercase
no such image: ghcr.io/Arquisoft/dede_es3b/restapi:latest: invalid reference format: repository name must be lowercase

**Comment by PascualDaniel** [comment]
Se ve en aqui: https://github.com/Arquisoft/dede_es3b/runs/6141762143

**Comment by PascualDaniel** [comment]
Ya esta solucionado, era que arquisoft estaba en mayúscula
