### ISSUE TITLE
Arreglar error de conexión con la base de datos en el despliegue.

### ISSUE THREAD

**Issue by PascualDaniel** [Arquisoft/dede_es3b#171]
Por ahora no se ve el catalogo, da error de conexion con mongo

**Comment by HugoLebredo** [comment]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/58787059/165294101-2ee8ba35-e3b9-4e9a-a88b-5d9b8ada637a.png">
 Parece que el error se encuentra aqui. Al no poder acceder al archivo env CI no pasa la cadena de conexión y peta.

Intentad crear un secret en el repo con la url de bbdd.

Otra opción menos elegante es copiar la url directamente. en la conexión.

A ver si con eso funciona

**Comment by PascualDaniel** [comment]
Creo que es asi:
![image](https://user-images.githubusercontent.com/71436553/165586507-d9f9cb30-b991-45db-be00-92c5a99a57c9.png)

**Comment by PascualDaniel** [comment]
Sigue sin funcionar y no parece que sea nada se la webapp, porque se pueden hacer peticiones pero no se recogen o tardan mucho

**Comment by Martin788** [comment]
El problema se arregló colocando la URI de conexión hardcodeada en la clase db.ts en vez de cogerlo del fichero .env
