### ISSUE TITLE
Problema a la hora de probar los test e2e

### ISSUE THREAD

**Issue by joserr-01** [Arquisoft/dede_es3b#174]
Estamos intentando probar un test e2e pero no estamos seguros de el comando que hay que ejecutar para ello. 
Hemos probado a ejecutar npm --prefix webapp run test:e2e. Al lanzar este comando se inicia la base de datos y la web app pero se queda parado hasta que se lanza una excepción de timeout.
No se si existe otra forma.

**Comment by HugoLebredo** [comment]
teneis que ejecutar el comando **build** primero, vereis que os creará un directorio llamado *build*. Es necesario que esté creado para a continuación, ejecutar el comando **test:e2e** del package.json del directorio webapp.

**Comment by Martin788** [comment]
El problema ahora es que al ejecutar el test:e2e nos aparece un error de que "jest no se reconoce como comando interno o externo, programa o archivo por lotes ejecutable"
