### ISSUE TITLE
Pull Request para practicar.

### ISSUE THREAD

**Issue by PascualDaniel** [Arquisoft/dede_es3b#4]
Para practicar con lar Pull Request estaria bien que cada compañero haga una.
Por ejemplo que ponga su nombre al final del readme, como hice yo en https://github.com/Arquisoft/dede_es3b/pull/1

**Comment by HugoLebredo** [comment]
👍💪

**Comment by UO277348** [comment]
Fechu guajes https://github.com/Arquisoft/dede_es3b/pull/6#issue-1121110162

**Comment by Martin788** [comment]
Ahí va https://github.com/Arquisoft/dede_es3b/pull/7#issue-1121114383

**Comment by uo277084** [comment]
Siiu https://github.com/Arquisoft/dede_es3b/pull/8#issue-1121122205

**Comment by joserr-01** [comment]
Hecho https://github.com/Arquisoft/dede_es3b/pull/9#issue-1122027018

**Comment by HugoLebredo** [comment]
Cuando lo hallais hecho todos cerrad el [issue02](https://github.com/Arquisoft/dede_es3b/issues/10)
