### ISSUE TITLE
Pregunta sobre las fotos de los proyectos

### ISSUE THREAD

**Issue by uo277084** [Arquisoft/dede_es3b#94]
¿Cuál era el repositorio para subir las imágenes que comentaste en clase?

**Comment by PascualDaniel** [comment]
Encontré esto:
https://cloudinary.com/documentation/node_integration

**Comment by UO277348** [comment]
@HugoLebredo

**Comment by HugoLebredo** [comment]
Hola Pablo.
 
Existen servicios que permiten almacenar imágenes en la nube y que puedas acceder a ellas a través de su API. Yo conozco Cloudinary. Te paso el enlace del paquete de npm. Esta bien documentada, tiene una guía de inicio y vas a encontrar muchos videos.
 
Basicamente necesitais 2 funciones para acceder a las imágenes
https://www.npmjs.com/package/cloudinary
 
Un saludo
