### ISSUE TITLE
Que API de distancias utilizar.

### ISSUE THREAD

**Issue by PascualDaniel** [Arquisoft/dede_es3b#95]
Para calcular la distancia entre dos puntos estoy buscando Apis, por ahora encontré varias pero tengo que hacer pruebas para ver si funcionan.
Las encontradas son:

- Bing
- Google
- [Route?](https://docs.microsoft.com/en-us/bingmaps/rest-services/routes/calculate-a-route?redirectedfrom=MSDN)

**Comment by PascualDaniel** [comment]
@HugoLebredo que API nos comentaste en clase?

**Comment by HugoLebredo** [comment]
Hay bastantes por ejemplo esta creo que está bastante bien https://www.shippypro.com/en/api/
creo que buscando "carrier api" en google puedes encontrar varias.

**Comment by PascualDaniel** [comment]
Ya esta cree la cuenta de shippypro y este es el esquema del envio

{
  "Method": "Ship",
  "Params": {
    "to_address": {
      "name": "John Doe",
      "company": "",
      "street1": "123 Main St",
      "street2": "",
      "city": "Park City",
      "state": "UT",
      "zip": "84060",
      "country": "US",
      "phone": "5551231234",
      "email": "johndoe@gmail.com"
    },
    "from_address": {
      "name": "John Doe",
      "company": "",
      "street1": "123 Main St",
      "street2": "",
      "city": "Park City",
      "state": "UT",
      "zip": "84060",
      "country": "US",
      "phone": "5551231234",
      "email": "johndoe@gmail.com"
    },
    "parcels": [
      {
        "length": 5,
        "width": 5,
        "height": 5,
        "weight": 10
      }
    ],
    "TotalValue": "123 EUR",
    "TransactionID": "ORDER2365",
    "ContentDescription": "Milk",
    "Insurance": 0,
    "InsuranceCurrency": "EUR",
    "CashOnDelivery": 0,
    "CashOnDeliveryCurrency": "EUR",
    "CashOnDeliveryType": 0,
    "CarrierName": "DHLExpress",
    "CarrierService": "EXPRESS DOMESTIC",
    "CarrierID": 23,
    "OrderID": "",
    "RateID": "14922625303744",
    "Incoterm": "DAP",
    "BillAccountNumber": "",
    "PaymentMethod": "Paypal",
    "Note": "Ship by 25/06/2018",
    "Async": false
  }
}

**Comment by PascualDaniel** [comment]
La respuesta:

{
  "Result": "OK",
  "NewOrderID": "1234567",
  "LabelURL": [
    "https://cdn.shippypro.com/labels/first_label.zpl",
    "https://cdn.shippypro.com/labels/second_label.zpl"
  ],
  "PDF": [],
  "ZPL": [
    "myzpllabel1...",
    "myzpllabel2..."
  ],
  "TrackingCarrier": "SpringXBS",
  "TrackingNumber": "UD26123123456",
  "TrackingExternalLink": "https://mailingtechnology.com/tracking/?tn=UD26123123456",
  "AdditionalTrackingNumbers": [],
  "Status": "1"
}

**Comment by PascualDaniel** [comment]
Se podría solo guardar el id en la base de datos y así nos podríamos ahorrar guardar lo demás.

**Comment by PascualDaniel** [comment]
ShippiPro parece que no funciona en España, aparte solo tiene 30 peticiones en su versión gratis, por lo que seria mejor optar por otra, [aqui](https://github.com/Arquisoft/dede_es3b/issues/109) señalo otra api que nos conviene mejor
